#!/bin/bash 
VER=`cat VERSION`;
reldir=../rel/v$VER;
cwd=`pwd`
echo $reldir
vcp(){
  mkdir -p $reldir/mintty/$2
  cp $1 $reldir/mintty/$2/$3
}
set -v
vcp cygwin/minttyrc               etc
vcp bin/mintty.exe                bin
vcp tools/mintheme                bin
vcp LICENSE                       share/doc/mintty
vcp LICENSE.GPL                   share/doc/mintty 
vcp LICENSE.Oxygen                share/doc/mintty
vcp LICENSE.PuTTY                 share/doc/mintty
vcp LICENSE.bundling              share/doc/mintty
vcp cygwin/README                 share/doc/mintty
vcp cygwin/setup.hint             share/doc/mintty
vcp docs/mintty.1                 share/man/man1
vcp tools/getemojis               share/mintty/emojis
vcp icon/\*.ico                   share/mintty/icon
vcp lang/\*.po                    share/mintty/lang
vcp sounds/\*.wav                 share/mintty/sounds
vcp themes/\*                     share/mintty/themes
gzip -rf $reldir/mintty/share/man
strip $reldir/mintty/bin/mintty.exe
cd $reldir
zip -r mintty-$VER.zip mintty
cd $cwd
mkdir -p dist
\cp  $reldir/mintty-$VER.zip dist/mintty.zip


