#!/bin/bash 
VER=`cat VERSION`;
reldir=../rel/v$VER;
cwd=`pwd`
echo $reldir
vcp(){
  mkdir -p $reldir/mintty/$2
  cp $1 $reldir/mintty/$2/$3
}
set -v
rm -f $reldir/mintty/share/man/*/*.gz
vcp cygwin/minttyrc               etc
vcp bin/mintty.exe                bin
vcp tools/mintheme                bin
vcp LICENSE                       usr/share/doc/mintty
vcp LICENSE.GPL                   usr/share/doc/mintty 
vcp LICENSE.Oxygen                usr/share/doc/mintty
vcp LICENSE.PuTTY                 usr/share/doc/mintty
vcp LICENSE.bundling              usr/share/doc/mintty
vcp cygwin/README                 usr/share/doc/mintty
vcp cygwin/setup.hint             usr/share/doc/mintty
vcp docs/mintty.1                 usr/share/man/man1
vcp tools/getemojis               usr/share/mintty/emojis
vcp icon/\*.ico                   usr/share/mintty/icon
vcp lang/\*.po                    usr/share/mintty/lang
vcp sounds/\*.wav                 usr/share/mintty/sounds
vcp themes/\*                     usr/share/mintty/themes
gzip -r $reldir/mintty/share/man
strip $reldir/mintty/bin/mintty.exe
cd $reldir
rm -f mintty-$VER.zip
zip -r mintty-$VER.zip mintty
cd $cwd
mkdir -p dist
\cp  $reldir/mintty-$VER.zip dist/mintty.zip


