//===============================================
#ifdef CFGDEFT 
#define DEFVAR 18971
#define DEFVAL 18972
#define DEFCFG 18973
#if CFGDEFT == DEFVAR
#define _CFGDEFA(t,T,n,v,c,d) t v;
#define _CFGDEFB(t,T,n,v,c,d) 
#define _CFGDEFC(t,T,n,v,c,d) 
#define _CFGDEFD(t,T,n,v,c,d) t v;
#define _CFGDEFE(t,T,n,v,c,d) 
#elif CFGDEFT == DEFVAL
#define _CFGDEFA(t,T,n,v,c,d) 
#define _CFGDEFB(t,T,n,v,c,d) .v = d,
#define _CFGDEFC(t,T,n,v,c,d) 
#define _CFGDEFD(t,T,n,v,c,d) .v = d,
#define _CFGDEFE(t,T,n,v,c,d) 
#elif CFGDEFT == DEFCFG
#define _CFGDEFA(t,T,n,v,c,d) 
#define _CFGDEFB(t,T,n,v,c,d) {n , T, offcfg(v),__(c)},
#define _CFGDEFC(t,T,n,v,c,d) 
#define _CFGDEFD(t,T,n,v,c,d) {n , T, offcfg(v),__(c)},
#define _CFGDEFE(t,T,n,v,c,d) {n , T, offcfg(v),__(c)},
#else
#define _CFGDEFA(t,T,n,v,c,d) 
#define _CFGDEFB(t,T,n,v,c,d) .v = d,
#define _CFGDEFC(t,T,n,v,c,d) 
#define _CFGDEFD(t,T,n,v,c,d) .v = d,
#define _CFGDEFE(t,T,n,v,c,d) 
#endif
#define CLRP(F,B) {F,B}
#define FNT(N,S,W,B) {N,S,W,B}

  _CFGDEFC(colour   ,OPT_COMMENT           ,"Looks"                    ,0,0,0)
  _CFGDEFD(colour   ,OPT_CLR               ,"ForegroundColour"         ,fg_colour                   ,"ForegroundColour"         ,0xBFBFBF)
  _CFGDEFD(colour   ,OPT_CLR               ,"BackgroundColour"         ,bg_colour                   ,"BackgroundColour"         ,0)
  _CFGDEFD(colour   ,OPT_CLR               ,"BoldColour"               ,bold_colour                 ,"BoldColour"               ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"BlinkColour"              ,blink_colour                ,"BlinkColour"              ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"CursorColour"             ,cursor_colour               ,"CursorColour"             ,0xBFBFBF)
  _CFGDEFD(colour   ,OPT_CLR               ,"TekForegroundColour"      ,tek_fg_colour               ,"TekForegroundColour"      ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"TekBackgroundColour"      ,tek_bg_colour               ,"TekBackgroundColour"      ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"TekCursorColour"          ,tek_cursor_colour           ,"TekCursorColour"          ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"TekWriteThruColour"       ,tek_write_thru_colour       ,"TekWriteThruColour"       ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"TekDefocusedColour"       ,tek_defocused_colour        ,"TekDefocusedColour"       ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_INT               ,"TekGlow"                  ,tek_glow                    ,"TekGlow"                  ,1)
  _CFGDEFD(colour   ,OPT_INT               ,"TekStrap"                 ,tek_strap                   ,"TekStrap"                 ,0)
  _CFGDEFD(colour   ,OPT_CLR               ,"UnderlineColour"          ,underl_colour               ,"UnderlineColour"          ,0)
  _CFGDEFD(colour   ,OPT_CLR               ,"HoverColour"              ,hover_colour                ,"HoverColour"              ,0)

  _CFGDEFA(colourfg ,0                     ,                           ,ansi_colours[16]            ,                           ,0)
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"Black"                    ,ansi_colours[BLACK_I]       ,"Black"                    ,CLRP( RGB(  0,   0,   0), RGB(  0,   0,   0) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"Red"                      ,ansi_colours[RED_I]         ,"Red"                      ,CLRP( RGB(212,  44,  58), RGB(162,  30,  41) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"Green"                    ,ansi_colours[GREEN_I]       ,"Green"                    ,CLRP( RGB( 28, 168,   0), RGB( 28, 168,   0) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"Yellow"                   ,ansi_colours[YELLOW_I]      ,"Yellow"                   ,CLRP( RGB(192, 160,   0), RGB(192, 160,   0) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"Blue"                     ,ansi_colours[BLUE_I]        ,"Blue"                     ,CLRP( RGB(  0,  93, 255), RGB(  0,  32, 192) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"Magenta"                  ,ansi_colours[MAGENTA_I]     ,"Magenta"                  ,CLRP( RGB(177,  72, 198), RGB(134,  54, 150) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"Cyan"                     ,ansi_colours[CYAN_I]        ,"Cyan"                     ,CLRP( RGB(  0, 168, 154), RGB(  0, 168, 154) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"White"                    ,ansi_colours[WHITE_I]       ,"White"                    ,CLRP( RGB(191, 191, 191), RGB(191, 191, 191) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldBlack"                ,ansi_colours[BOLD_BLACK_I]  ,"BoldBlack"                ,CLRP( RGB( 96,  96,  96), RGB( 72,  72,  72) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldRed"                  ,ansi_colours[BOLD_RED_I]    ,"BoldRed"                  ,CLRP( RGB(255, 118, 118), RGB(255, 118, 118) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldGreen"                ,ansi_colours[BOLD_GREEN_I]  ,"BoldGreen"                ,CLRP( RGB(  0, 242,   0), RGB(  0, 242,   0) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldYellow"               ,ansi_colours[BOLD_YELLOW_I] ,"BoldYellow"               ,CLRP( RGB(242, 242,   0), RGB(242, 242,   0) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldBlue"                 ,ansi_colours[BOLD_BLUE_I]   ,"BoldBlue"                 ,CLRP( RGB(125, 151, 255), RGB(125, 151, 255) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldMagenta"              ,ansi_colours[BOLD_MAGENTA_I],"BoldMagenta"              ,CLRP( RGB(255, 112, 255), RGB(255, 112, 255) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldCyan"                 ,ansi_colours[BOLD_CYAN_I]   ,"BoldCyan"                 ,CLRP( RGB(  0, 240, 240), RGB(  0, 240, 240) ))
  _CFGDEFB(0        ,OPT_THEME|OPT_CLRFG   ,"BoldWhite"                ,ansi_colours[BOLD_WHITE_I]  ,"BoldWhite"                ,CLRP( RGB(255, 255, 255), RGB(255, 255, 255) ))
                                                                                                           
  _CFGDEFD(int      ,OPT_INT               ,"DispSpace"                ,disp_space                  ,"DispSpace"                ,0)
  _CFGDEFD(int      ,OPT_INT               ,"DispClear"                ,disp_clear                  ,"DispClear"                ,0)
  _CFGDEFD(int      ,OPT_INT               ,"DispTab"                  ,disp_tab                    ,"DispTab"                  ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"UnderlineManual"          ,underl_manual               ,"UnderlineManual"          ,0)
  _CFGDEFD(colour   ,OPT_CLR               ,"HighlightBackgroundColour",sel_bg_colour               ,"HighlightBackgroundColour",0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"HighlightForegroundColour",sel_fg_colour               ,"HighlightForegroundColour",0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR               ,"SearchForegroundColour"   ,search_fg_colour            ,"SearchForegroundColour"   ,0x000000)
  _CFGDEFD(colour   ,OPT_CLR               ,"SearchBackgroundColour"   ,search_bg_colour            ,"SearchBackgroundColour"   ,0x00DDDD)
  _CFGDEFD(colour   ,OPT_CLR               ,"SearchCurrentColour"      ,search_current_colour       ,"SearchCurrentColour"      ,0x0099DD)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"ThemeFile"                ,theme_file                  ,"ThemeFile"                ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"Background"               ,background                  ,"Background"               ,W(""))
  _CFGDEFD(string   ,OPT_STR               ,"ColourScheme"             ,colour_scheme               ,"ColourScheme"             ,"")
  _CFGDEFD(int      ,OPT_TRANS             ,"Transparency"             ,transparency                ,"Transparency"             ,0)
#ifdef support_blurred                                                                            
  _CFGDEFD(int      ,OPT_BOOL              ,"Blur"                     ,blurred                     ,"Blur"                     ,0)
#endif                                                                                               
  _CFGDEFD(int      ,OPT_BOOL              ,"OpaqueWhenFocused"        ,opaque_when_focused         ,"OpaqueWhenFocused"        ,0)
  _CFGDEFD(int      ,OPT_CURSOR            ,"CursorType"               ,cursor_type                 ,"CursorType"               ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"CursorBlinks"             ,cursor_blinks               ,"CursorBlinks"             ,0)
                                                                                                      
  _CFGDEFD(colour   ,OPT_CLR               ,"TabForegroundColour"      ,tab_fg_colour               ,"TabForegroundColour"      ,0x00FF00)
  _CFGDEFD(colour   ,OPT_CLR               ,"TabBackgroundColour"      ,tab_bg_colour               ,"TabBackgroundColour"      ,0x000000)
  _CFGDEFD(colour   ,OPT_CLR               ,"TabAttentionColour"       ,tab_attention_bg_colour     ,"TabAttentionColour"       ,0x323232)
  _CFGDEFD(colour   ,OPT_CLR               ,"TabActiveColour"          ,tab_active_bg_colour        ,"TabActiveColour"          ,0x003200)
  _CFGDEFD(int      ,OPT_BOOL              ,"tab_bar_show"             ,tab_bar_show                ,"tab_bar_show"             ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"indicator"                ,indicator                   ,"indicator"                ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"indicatorx"               ,indicatorx                  ,"indicatorx"               ,30)
  _CFGDEFD(int      ,OPT_BOOL              ,"indicatory"               ,indicatory                  ,"indicatory"               ,30)
  _CFGDEFD(int      ,OPT_BOOL              ,"tab_font_size"            ,tab_font_size               ,"tab_font_size"            ,16)
  _CFGDEFD(int      ,OPT_INT               ,"gui_font_size"            ,gui_font_size               ,"gui_font_size"            ,12)
  _CFGDEFD(int      ,OPT_INT               ,"scale_options_width"      ,scale_options_width         ,"scale_options_width"      ,100)
  _CFGDEFD(int      ,OPT_INT               ,"Padding"                  ,padding                     ,"Padding"                  ,1)
  _CFGDEFD(int      ,OPT_INT               ,"partline"                 ,partline                    ,"partline"                 ,4)
  _CFGDEFD(int      ,OPT_INT               ,"usepartline"              ,usepartline                 ,"usepartline"              ,0)
                                                                                                      
                                                                                                      
  _CFGDEFC(int      ,OPT_COMMENT           ,"Text"                     ,0,0,0)

  _CFGDEFD(font_spec,OPT_FONT              ,"Font"                     ,font                        ,"Font"                     ,FNT(W("Lucida Console"),16,400,0))
  _CFGDEFA(font_spec,0                     ,                           ,fontfams[12]                ,0                          ,0)
  _CFGDEFB(0        ,OPT_FONT              ,"Font1"                    ,fontfams[1]                 ,"Font1"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font2"                    ,fontfams[2]                 ,"Font2"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font3"                    ,fontfams[3]                 ,"Font3"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font4"                    ,fontfams[4]                 ,"Font4"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font5"                    ,fontfams[5]                 ,"Font5"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font6"                    ,fontfams[6]                 ,"Font6"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font7"                    ,fontfams[7]                 ,"Font7"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font8"                    ,fontfams[8]                 ,"Font8"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font9"                    ,fontfams[9]                 ,"Font9"                    ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"Font10"                   ,fontfams[10]                ,"Font10"                   ,FNT(W(""),16,400,0))
  _CFGDEFB(0        ,OPT_FONT              ,"FontRTL"                  ,fontfams[11]                ,"FontRTL"                  ,FNT(W("Courier New"),16,400,0))
                                                                                                      
  _CFGDEFD(wstring  ,OPT_WSTR              ,"FontChoice"               ,font_choice                 ,"FontChoice"               ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"FontSample"               ,font_sample                 ,"FontSample"               ,W(""))
  _CFGDEFD(int      ,OPT_BOOL              ,"ShowHiddenFonts"          ,show_hidden_fonts           ,"ShowHiddenFonts"          ,0)
  _CFGDEFD(int      ,OPT_FONTSMT           ,"FontSmoothing"            ,font_smoothing              ,"FontSmoothing"            ,FS_DEFAULT)
  _CFGDEFD(int      ,OPT_FONTRENDER        ,"FontRender"               ,font_render                 ,"FontRender"               ,FR_UNISCRIBE)
  _CFGDEFD(int      ,OPT_BOOL              ,"BoldAsFont"               ,bold_as_font                ,"BoldAsFont"               ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"BoldAsColour"             ,bold_as_colour              ,"BoldAsColour"             ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"AllowBlinking"            ,allow_blinking              ,"AllowBlinking"            ,0)
  _CFGDEFD(string   ,OPT_STR               ,"Locale"                   ,locale                      ,"Locale"                   ,"")
  _CFGDEFD(string   ,OPT_STR               ,"Charset"                  ,charset                     ,"Charset"                  ,"")
  _CFGDEFD(int      ,OPT_CHARWIDTH         ,"Charwidth"                ,charwidth                   ,"Charwidth"                ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"OldLocale"                ,old_locale                  ,"OldLocale"                ,0)
  _CFGDEFD(int      ,OPT_INT               ,"FontMenu"                 ,fontmenu                    ,"FontMenu"                 ,-1)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"TekFont"                  ,tek_font                    ,"TekFont"                  ,W(""))
                                                                                                      
                                                                                                      
  _CFGDEFC(int      ,OPT_COMMENT           ,"Keys"                     ,0,0,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"BackspaceSendsBS"         ,backspace_sends_bs          ,"BackspaceSendsBS"         ,'\b')
  _CFGDEFD(int      ,OPT_BOOL              ,"DeleteSendsDEL"           ,delete_sends_del            ,"DeleteSendsDEL"           ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"CtrlAltIsAltGr"           ,ctrl_alt_is_altgr           ,"CtrlAltIsAltGr"           ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"AltGrIsAlsoAlt"           ,altgr_is_alt                ,"AltGrIsAlsoAlt"           ,0)
  _CFGDEFD(int      ,OPT_INT               ,"CtrlAltDelayAltGr"        ,ctrl_alt_delay_altgr        ,"CtrlAltDelayAltGr"        ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"OldAltGrDetection"        ,old_altgr_detection         ,"OldAltGrDetection"        ,0)
  _CFGDEFD(int      ,OPT_INT               ,"OldModifyKeys"            ,old_modify_keys             ,"OldModifyKeys"            ,0)
  _CFGDEFD(int      ,OPT_INT               ,"FormatOtherKeys"          ,format_other_keys           ,"FormatOtherKeys"          ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"AutoRepeat"               ,auto_repeat                 ,"AutoRepeat"               ,1)
  _CFGDEFD(int      ,OPT_INT               ,"SupportExternalHotkeys"   ,external_hotkeys            ,"SupportExternalHotkeys"   ,2)
  _CFGDEFD(int      ,OPT_BOOL              ,"ClipShortcuts"            ,clip_shortcuts              ,"ClipShortcuts"            ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"WindowShortcuts"          ,window_shortcuts            ,"WindowShortcuts"          ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"SwitchShortcuts"          ,switch_shortcuts            ,"SwitchShortcuts"          ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"ZoomShortcuts"            ,zoom_shortcuts              ,"ZoomShortcuts"            ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"ZoomFontWithWindow"       ,zoom_font_with_window       ,"ZoomFontWithWindow"       ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"AltFnShortcuts"           ,alt_fn_shortcuts            ,"AltFnShortcuts"           ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"WinShortcuts"             ,win_shortcuts               ,"WinShortcuts"             ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"hkwinkeyall"              ,hkwinkeyall                 ,"hkwinkeyall"              ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"hook_keyboard"            ,hook_keyboard               ,"hook_keyboard"            ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"CtrlShiftShortcuts"       ,ctrl_shift_shortcuts        ,"CtrlShiftShortcuts"       ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"CtrlExchangeShift"        ,ctrl_exchange_shift         ,"CtrlExchangeShift"        ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"CtrlControls"             ,ctrl_controls               ,"CtrlControls"             ,0)
  _CFGDEFD(int      ,OPT_COMPOSE_KEY       ,"ComposeKey"               ,compose_key                 ,"ComposeKey"               ,0)
  _CFGDEFD(string   ,OPT_STR               ,"Key_PrintScreen"          ,key_prtscreen               ,"Key_PrintScreen"          ,"")    // VK_SNAPSHOT
  _CFGDEFD(string   ,OPT_STR               ,"Key_Pause"                ,key_pause                   ,"Key_Pause"                ,"")  // VK_PAUSE
  _CFGDEFD(string   ,OPT_STR               ,"Key_Break"                ,key_break                   ,"Key_Break"                ,"")  // VK_CANCEL
  _CFGDEFD(string   ,OPT_STR               ,"Key_Menu"                 ,key_menu                    ,"Key_Menu"                 ,"")    // VK_APPS
  _CFGDEFD(string   ,OPT_STR               ,"Key_ScrollLock"           ,key_scrlock                 ,"Key_ScrollLock"           ,"")    // VK_SCROLL
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"KeyFunctions"             ,key_commands                ,"KeyFunctions"             ,W(""))
  _CFGDEFD(int      ,OPT_INT               ,"ManageLEDs"               ,manage_leds                 ,"ManageLEDs"               ,7)
  _CFGDEFD(int      ,OPT_BOOL              ,"ShootFoot"                ,enable_remap_ctrls          ,"ShootFoot"                ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"OldKeyFunctionsKeypad"    ,old_keyfuncs_keypad         ,"OldKeyFunctionsKeypad"    ,0)
                                                                                                      
                                                                                                      
  _CFGDEFC(int      ,OPT_COMMENT           ,"Mouse"                    ,0,0,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"ClicksPlaceCursor"        ,clicks_place_cursor         ,"ClicksPlaceCursor"        ,0)
  _CFGDEFD(int      ,OPT_MIDDLECLICK       ,"MiddleClickAction"        ,middle_click_action         ,"MiddleClickAction"        ,MC_PASTE)
  _CFGDEFD(int      ,OPT_RIGHTCLICK        ,"RightClickAction"         ,right_click_action          ,"RightClickAction"         ,RC_MENU)
  _CFGDEFD(int      ,OPT_INT               ,"OpeningClicks"            ,opening_clicks              ,"OpeningClicks"            ,1)
  _CFGDEFD(int      ,OPT_MOD               ,"OpeningMod"               ,opening_mod                 ,"OpeningMod"               ,MDK_CTRL)
  _CFGDEFD(int      ,OPT_BOOL              ,"ZoomMouse"                ,zoom_mouse                  ,"ZoomMouse"                ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"ClicksTargetApp"          ,clicks_target_app           ,"ClicksTargetApp"          ,1)
  _CFGDEFD(int      ,OPT_MOD               ,"ClickTargetMod"           ,click_target_mod            ,"ClickTargetMod"           ,MDK_SHIFT)
  _CFGDEFD(int      ,OPT_BOOL              ,"HideMouse"                ,hide_mouse                  ,"HideMouse"                ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"ElasticMouse"             ,elastic_mouse               ,"ElasticMouse"             ,0)
  _CFGDEFD(int      ,OPT_INT               ,"LinesPerMouseWheelNotch"  ,lines_per_notch             ,"LinesPerMouseWheelNotch"  ,0)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"MousePointer"             ,mouse_pointer               ,"MousePointer"             ,W("ibeam"))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"AppMousePointer"          ,appmouse_pointer            ,"AppMousePointer"          ,W("arrow"))
  _CFGDEFC(int      ,OPT_COMMENT           ,"Selection"                ,0,0,0) // Selection
  _CFGDEFD(int      ,OPT_BOOL              ,"ClearSelectionOnInput"    ,input_clears_selection      ,"ClearSelectionOnInput"    ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"CopyOnSelect"             ,copy_on_select              ,"CopyOnSelect"             ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"CopyTab"                  ,copy_tabs                   ,"CopyTab"                  ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"CopyAsRTF"                ,copy_as_rtf                 ,"CopyAsRTF"                ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"CopyAsHTML"               ,copy_as_html                ,"CopyAsHTML"               ,0)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"CopyAsRTFFont"            ,copy_as_rtf_font            ,"CopyAsRTFFont"            ,W(""))
  _CFGDEFD(int      ,OPT_INT               ,"CopyAsRTFFontHeight"      ,copy_as_rtf_font_size       ,"CopyAsRTFFontHeight"      ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"TrimSelection"            ,trim_selection              ,"TrimSelection"            ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"AllowSetSelection"        ,allow_set_selection         ,"AllowSetSelection"        ,0)
  _CFGDEFD(int      ,OPT_INT               ,"SelectionShowSize"        ,selection_show_size         ,"SelectionShowSize"        ,0)
  _CFGDEFC(int      ,OPT_COMMENT           ,"Window"                   ,0,0,0)  // Window
  _CFGDEFD(int      ,OPT_INT               ,"Columns"                  ,cols                        ,"Columns"                  ,80)
  _CFGDEFD(int      ,OPT_INT               ,"Rows"                     ,rows                        ,"Rows"                     ,24)
  _CFGDEFD(int      ,OPT_BOOL              ,"RewrapOnResize"           ,rewrap_on_resize            ,"RewrapOnResize"           ,0)
  _CFGDEFD(int      ,OPT_SCROLLBAR         ,"Scrollbar"                ,scrollbar                   ,"Scrollbar"                ,1)
  _CFGDEFD(int      ,OPT_INT               ,"ScrollbackLines"          ,scrollback_lines            ,"ScrollbackLines"          ,10000)
  _CFGDEFD(int      ,OPT_INT               ,"MaxScrollbackLines"       ,max_scrollback_lines        ,"MaxScrollbackLines"       ,250000)
  _CFGDEFD(int      ,OPT_MOD               ,"ScrollMod"                ,scroll_mod                  ,"ScrollMod"                ,MDK_SHIFT)
  _CFGDEFD(int      ,OPT_BOOL              ,"PgUpDnScroll"             ,pgupdn_scroll               ,"PgUpDnScroll"             ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"allocconsole"             ,allocconsole                ,"allocconsole"             ,0)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"Language"                 ,lang                        ,"Language"                 ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"SearchBar"                ,search_bar                  ,"SearchBar"                ,W(""))
  _CFGDEFD(int      ,OPT_INT               ,"SearchContext"            ,search_context              ,"SearchContext"            ,0)
  _CFGDEFC(int      ,OPT_COMMENT           ,"Terminal"                 ,0,0,0)  // Terminal
  _CFGDEFD(string   ,OPT_STR               ,"Term"                     ,Term                        ,"Term"                     ,"xterm")
  _CFGDEFD(string   ,OPT_STR               ,"Answerback"               ,answerback                  ,"Answerback"               ,"")
  _CFGDEFD(int      ,OPT_INT               ,"WrapTab"                  ,wrap_tab                    ,"WrapTab"                  ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"OldWrapModes"             ,old_wrapmodes               ,"OldWrapModes"             ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"Enable132ColumnSwitching" ,enable_deccolm_init         ,"Enable132ColumnSwitching" ,0)
  _CFGDEFD(int      ,OPT_INT               ,"BellType"                 ,bell_type                   ,"BellType"                 ,1)
  _CFGDEFA(wstring  ,0                     ,0                          ,bell_file[7]                ,0                          ,0)
  _CFGDEFB(wstring  ,OPT_WSTR              ,"BellFile"                 ,bell_file[6]                ,"BellFile"                 ,W(""))
  _CFGDEFB(wstring  ,OPT_WSTR              ,"BellFile2"                ,bell_file[0]                ,"BellFile2"                ,W(""))
  _CFGDEFB(wstring  ,OPT_WSTR              ,"BellFile3"                ,bell_file[1]                ,"BellFile3"                ,W(""))
  _CFGDEFB(wstring  ,OPT_WSTR              ,"BellFile4"                ,bell_file[2]                ,"BellFile4"                ,W(""))
  _CFGDEFB(wstring  ,OPT_WSTR              ,"BellFile5"                ,bell_file[3]                ,"BellFile5"                ,W(""))
  _CFGDEFB(wstring  ,OPT_WSTR              ,"BellFile6"                ,bell_file[4]                ,"BellFile6"                ,W(""))
  _CFGDEFB(wstring  ,OPT_WSTR              ,"BellFile7"                ,bell_file[5]                ,"BellFile7"                ,W(""))
  _CFGDEFD(int      ,OPT_INT               ,"BellFreq"                 ,bell_freq                   ,"BellFreq"                 ,0)
  _CFGDEFD(int      ,OPT_INT               ,"BellLen"                  ,bell_len                    ,"BellLen"                  ,400)
  _CFGDEFD(int      ,OPT_BOOL              ,"BellFlash"                ,bell_flash                  ,"BellFlash"                ,0)// xterm: visualBell
  _CFGDEFD(int      ,OPT_INT               ,"BellFlashStyle"           ,bell_flash_style            ,"BellFlashStyle"           ,FLASH_FULL)
  _CFGDEFD(int      ,OPT_BOOL              ,"BellTaskbar"              ,bell_taskbar                ,"BellTaskbar"              ,1)// xterm: bellIsUrgent
  _CFGDEFD(int      ,OPT_BOOL              ,"BellPopup"                ,bell_popup                  ,"BellPopup"                ,0)// xterm: popOnBell
  _CFGDEFD(int      ,OPT_INT               ,"BellInterval"             ,bell_interval               ,"BellInterval"             ,100)
  _CFGDEFD(int      ,OPT_INT               ,"PlayTone"                 ,play_tone                   ,"PlayTone"                 ,2)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"Printer"                  ,printer                     ,"Printer"                  ,W(""))
  _CFGDEFD(int      ,OPT_BOOL              ,"ConfirmExit"              ,confirm_exit                ,"ConfirmExit"              ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"ConfirmReset"             ,confirm_reset               ,"ConfirmReset"             ,0)
  _CFGDEFC(int      ,OPT_COMMENT           ,"Command line"             ,0,0,0)  // Command line
  _CFGDEFD(wstring  ,OPT_WSTR              ,"Class"                    ,class                       ,"Class"                    ,W(""))
  _CFGDEFD(int      ,OPT_HOLD              ,"Hold"                     ,hold                        ,"Hold"                     ,HOLD_START)
  _CFGDEFD(int      ,OPT_BOOL              ,"ExitWrite"                ,exit_write                  ,"ExitWrite"                ,0)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"ExitTitle"                ,exit_title                  ,"ExitTitle"                ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"Icon"                     ,icon                        ,"Icon"                     ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"Log"                      ,log                         ,"Log"                      ,W(""))
  _CFGDEFD(int      ,OPT_INT               ,"Logging"                  ,logging                     ,"Logging"                  ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"Utmp"                     ,create_utmp                 ,"Utmp"                     ,0)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"Title"                    ,title                       ,"Title"                    ,W(""))
  _CFGDEFD(int      ,OPT_BOOL              ,"title_settable"           ,title_settable              ,"title_settable"           ,1)
  _CFGDEFD(int      ,OPT_WINDOW            ,"Window"                   ,window                      ,"Window"                   ,0)
  _CFGDEFD(int      ,OPT_INT               ,"X"                        ,x                           ,"X"                        ,0)
  _CFGDEFD(int      ,OPT_INT               ,"Y"                        ,y                           ,"Y"                        ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"Daemonize"                ,daemonize                   ,"Daemonize"                ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"DaemonizeAlways"          ,daemonize_always            ,"DaemonizeAlways"          ,0)
  _CFGDEFC(int      ,OPT_COMMENT           ,"Hidden"                   ,0,0,0)  // "Hidden"
  _CFGDEFD(int      ,OPT_INT               ,"Bidi"                     ,bidi                        ,"Bidi"                     ,2)
  _CFGDEFD(int      ,OPT_BOOL              ,"NoAltScreen"              ,disable_alternate_screen    ,"NoAltScreen"              ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"EraseToScrollback"        ,erase_to_scrollback         ,"EraseToScrollback"        ,1)
  _CFGDEFD(int      ,OPT_INT               ,"DisplaySpeedup"           ,display_speedup             ,"DisplaySpeedup"           ,6)
  _CFGDEFD(string   ,OPT_STR               ,"SuppressSGR"              ,suppress_sgr                ,"SuppressSGR"              ,"")
  _CFGDEFD(string   ,OPT_STR               ,"SuppressDEC"              ,suppress_dec                ,"SuppressDEC"              ,"")
  _CFGDEFD(string   ,OPT_STR               ,"SuppressWIN"              ,suppress_win                ,"SuppressWIN"              ,"")
  _CFGDEFD(string   ,OPT_STR               ,"SuppressOSC"              ,suppress_osc                ,"SuppressOSC"              ,"")
  _CFGDEFD(string   ,OPT_STR               ,"SuppressNRC"              ,suppress_nrc                ,"SuppressNRC"              ,"")
  _CFGDEFD(string   ,OPT_STR               ,"SuppressMouseWheel"       ,suppress_wheel              ,"SuppressMouseWheel"       ,"")
  _CFGDEFD(string   ,OPT_STR               ,"FilterPasteControls"      ,filter_paste                ,"FilterPasteControls"      ,"")
  _CFGDEFD(int      ,OPT_INT               ,"BracketedPasteByLine"     ,bracketed_paste_split       ,"BracketedPasteByLine"     ,0)
  _CFGDEFD(int      ,OPT_INT               ,"SuspendWhileSelecting"    ,suspbuf_max                 ,"SuspendWhileSelecting"    ,8080)
  _CFGDEFD(int      ,OPT_INT               ,"PrintableControls"        ,printable_controls          ,"PrintableControls"        ,0)
  _CFGDEFD(int      ,OPT_INT               ,"CharNarrowing"            ,char_narrowing              ,"CharNarrowing"            ,75)
  _CFGDEFD(int      ,OPT_EMOJIS            ,"Emojis"                   ,emojis                      ,"Emojis"                   ,0)
  _CFGDEFD(int      ,OPT_EMOJI_PLACEMENT   ,"EmojiPlacement"           ,emoji_placement             ,"EmojiPlacement"           ,EMPL_STRETCH)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"SaveFilename"             ,save_filename               ,"SaveFilename"             ,W("mintty.%Y-%m-%d_%H-%M-%S"))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"AppID"                    ,app_id                      ,"AppID"                    ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"AppName"                  ,app_name                    ,"AppName"                  ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"AppLaunchCmd"             ,app_launch_cmd              ,"AppLaunchCmd"             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"DropCommands"             ,drop_commands               ,"DropCommands"             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"ExitCommands"             ,exit_commands               ,"ExitCommands"             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"UserCommands"             ,user_commands               ,"UserCommands"             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"CtxMenuFunctions"         ,ctx_user_commands           ,"CtxMenuFunctions"         ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"SysMenuFunctions"         ,sys_user_commands           ,"SysMenuFunctions"         ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR              ,"UserCommandsPath"         ,user_commands_path          ,"UserCommandsPath"         ,W("/bin:%s"))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"SessionCommands"          ,session_commands            ,"SessionCommands"          ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KEEPCR   ,"TaskCommands"             ,task_commands               ,"TaskCommands"             ,W(""))
  _CFGDEFD(int      ,OPT_BOOL              ,"ConPTY"                   ,conpty_support              ,"ConPTY"                   ,-1)
  _CFGDEFD(int      ,OPT_BOOL              ,"LoginFromShortcut"        ,login_from_shortcut         ,"LoginFromShortcut"        ,1)
  _CFGDEFD(string   ,OPT_STR               ,"MenuMouse"                ,menu_mouse                  ,"MenuMouse"                ,"b")
  _CFGDEFD(string   ,OPT_STR               ,"MenuCtrlMouse"            ,menu_ctrlmouse              ,"MenuCtrlMouse"            ,"e|ls")
  _CFGDEFD(string   ,OPT_STR               ,"MenuMouse5"               ,menu_altmouse               ,"MenuMouse5"               ,"ls"  )
  _CFGDEFD(string   ,OPT_STR               ,"MenuMenu"                 ,menu_menu                   ,"MenuMenu"                 ,"bs"  )
  _CFGDEFD(string   ,OPT_STR               ,"MenuCtrlMenu"             ,menu_ctrlmenu               ,"MenuCtrlMenu"             ,"e|ls")
  _CFGDEFD(string   ,OPT_STR               ,"MenuTitleCtrlLeft"        ,menu_title_ctrl_l           ,"MenuTitleCtrlLeft"        ,"Ws")
  _CFGDEFD(string   ,OPT_STR               ,"MenuTitleCtrlRight"       ,menu_title_ctrl_r           ,"MenuTitleCtrlRight"       ,"Ws")
  _CFGDEFD(int      ,OPT_INT               ,"SessionGeomSync"          ,geom_sync                   ,"SessionGeomSync"          ,0)
  _CFGDEFD(int      ,OPT_INT               ,"ColSpacing"               ,col_spacing                 ,"ColSpacing"               ,0)
  _CFGDEFD(int      ,OPT_INT               ,"RowSpacing"               ,row_spacing                 ,"RowSpacing"               ,0)
  _CFGDEFD(int      ,OPT_INT               ,"AutoLeading"              ,auto_leading                ,"AutoLeading"              ,2)
  _CFGDEFD(int      ,OPT_INT               ,"Ligatures"                ,ligatures                   ,"Ligatures"                ,1)
  _CFGDEFD(int      ,OPT_INT               ,"LigaturesSupport"         ,ligatures_support           ,"LigaturesSupport"         ,0)
  _CFGDEFD(int      ,OPT_INT               ,"HandleDPI"                ,handle_dpichanged           ,"HandleDPI"                ,2)
  _CFGDEFD(int      ,OPT_INT               ,"CheckVersionUpdate"       ,check_version_update        ,"CheckVersionUpdate"       ,0)
  _CFGDEFD(string   ,OPT_STR               ,"WordChars"                ,word_chars                  ,"WordChars"                ,"")
  _CFGDEFD(string   ,OPT_STR               ,"WordCharsExcl"            ,word_chars_excl             ,"WordCharsExcl"            ,"")
  _CFGDEFD(colour   ,OPT_CLR               ,"IMECursorColour"          ,ime_cursor_colour           ,"IMECursorColour"          ,DEFAULT_COLOUR)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"SixelClipChars"           ,sixel_clip_char             ,"SixelClipChars"           ,W(""))
  _CFGDEFD(int      ,OPT_BOOL              ,"ShortLongOpts"            ,short_long_opts             ,"ShortLongOpts"            ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"BoldAsRainbowSparkles"    ,bold_as_special             ,"BoldAsRainbowSparkles"    ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"HoverTitle"               ,hover_title                 ,"HoverTitle"               ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"ProgressBar"              ,progress_bar                ,"ProgressBar"              ,0)
  _CFGDEFD(int      ,OPT_INT               ,"ProgressScan"             ,progress_scan               ,"ProgressScan"             ,1)
  _CFGDEFD(int      ,OPT_BOOL              ,"DimMargins"               ,dim_margins                 ,"DimMargins"               ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"StatusLine"               ,status_line                 ,"StatusLine"               ,0)
  _CFGDEFD(int      ,OPT_INT               ,"Baud"                     ,baud                        ,"Baud"                     ,0)
  _CFGDEFD(int      ,OPT_INT               ,"Bloom"                    ,bloom                       ,"Bloom"                    ,0)
  _CFGDEFD(wstring  ,OPT_WSTR              ,"OptionsFont"              ,options_font                ,"OptionsFont"              ,W(""))
  _CFGDEFD(int      ,OPT_INT               ,"OptionsFontHeight"        ,options_fontsize            ,"OptionsFontHeight"        ,0)
  _CFGDEFD(string   ,OPT_STR               ,"OldOptions"               ,old_options                 ,"OldOptions"               ,"")
  _CFGDEFD(int      ,OPT_BOOL              ,"OldXButtons"              ,old_xbuttons                ,"OldXButtons"              ,0)
  _CFGDEFD(int      ,OPT_INT               ,"WSLBridge"                ,wslbridge                   ,"wslbridge version,0:nobridge,1:wslbridge,2:wslbreadge2" ,0)
  _CFGDEFD(string   ,OPT_STR               ,"WSLName"                  ,wslname                     ,"wslDistribution,null is default" ,"")
                                                                                                      
  // Legacy

  _CFGDEFE(int      ,OPT_INT|OPT_LEGACY    ,"FontSize"                 ,font.size                   ,"FontSize"                 ,0)
  _CFGDEFE(string   ,OPT_STR|OPT_LEGACY    ,"Break"                    ,key_break                   ,"Break"                    ,0)
  _CFGDEFE(string   ,OPT_STR|OPT_LEGACY    ,"Pause"                    ,key_pause                   ,"Pause"                    ,0)
  _CFGDEFE(int      ,OPT_INT|OPT_LEGACY    ,"CopyAsRTFFontSize"        ,copy_as_rtf_font_size       ,"CopyAsRTFFontSize"        ,0)
  _CFGDEFE(int      ,OPT_INT|OPT_LEGACY    ,"OldFontMenu"              ,fontmenu                    ,"OldFontMenu"              ,0)
  _CFGDEFE(int      ,OPT_INT|OPT_LEGACY    ,"OptionsFontSize"          ,options_fontsize            ,"OptionsFontSize"          ,0)
  _CFGDEFE(int      ,OPT_BOOL|OPT_LEGACY   ,"BoldAsBright"             ,bold_as_colour              ,"BoldAsBright"             ,0)
  _CFGDEFE(int      ,OPT_FONTSMT|OPT_LEGACY,"FontQuality"              ,font_smoothing              ,"FontQuality"              ,0)

  _CFGDEFD(colour   ,OPT_BOOL|OPT_LEGACY   ,"UseSystemColours"         ,use_system_colours          ,"UseSystemColours"         ,0)
  _CFGDEFD(int      ,OPT_BOOL              ,"OldBold"                  ,old_bold                    ,"OldBold"                  ,0)
#undef CFGDEFT  
#undef _CFGDEFA
#undef _CFGDEFB
#undef _CFGDEFC
#undef _CFGDEFD
#undef _CFGDEFE
#undef DEFVAR 
#undef DEFVAL 
#undef DEFCFG 
#endif
