//===============================================
#ifdef CFGDEFT 
// define variable in struct config ,included in config.h,
#define DEFVAR 18971
// define init value in default_cfg ,included in config.c
#define DEFVAL 18972
// define cfg_option ,included in config.c
#define DEFCFG 18973
/*
_CFGDEFA:Define array
_CFGDEFB:Define Array Elements 
_CFGDEFC: opt comment,novalue
_CFGDEFD: opt data
_CFGDEFE: Legacy options for Backward Compatibility
 */
#if CFGDEFT == DEFVAR
#define _CFGDEFA(t,T,F,l,n,v,c,d) t v;
#define _CFGDEFB(t,T,F,l,n,v,c,d) 
#define _CFGDEFa(t,T,F,l,n,v,c,d) t v;
#define _CFGDEFb(t,T,F,l,n,v,c,d) 
#define _CFGDEFC(t,T,F,l,n  ,c  ) 
#define _CFGDEFD(t,T,F,l,n,v,c,d) t v;
#define _CFGDEFE(t,T,F,l,n,v,c  ) 
#elif CFGDEFT == DEFVAL
#define _CFGDEFA(t,T,F,l,n,v,c,d) 
#define _CFGDEFa(t,T,F,l,n,v,c,d) .v = d, 
#define _CFGDEFB(t,T,F,l,n,v,c,d) .v = d,
#define _CFGDEFb(t,T,F,l,n,v,c,d) 
#define _CFGDEFC(t,T,F,l,n  ,c  ) 
#define _CFGDEFD(t,T,F,l,n,v,c,d) .v = d,
#define _CFGDEFE(t,T,F,l,n,v,c  ) 
#elif CFGDEFT == DEFCFG
#define _CFGDEFA(t,T,F,l,n,v,c,d) 
#define _CFGDEFa(t,T,F,l,n,v,c,d) {n , T,F,l, offcfg(v),c},
#define _CFGDEFB(t,T,F,l,n,v,c,d) {n , T,F,l, offcfg(v),c},
#define _CFGDEFb(t,T,F,l,n,v,c,d) {n , T,F,l, offcfg(v),c},
#define _CFGDEFC(t,T,F,l,n  ,c  ) {n , T,F,l, 0        ,c},
#define _CFGDEFD(t,T,F,l,n,v,c,d) {n , T,F,l, offcfg(v),c},
#define _CFGDEFE(t,T,F,l,n,v,c  ) {n , T,F,l, offcfg(v),c},
#else
#error "Error:include configdef.h must define CFGDEFT as DEFVAR,DEFVAL,DEFCFG"
#endif
#define CLRP(F,B) {F,B}
#define FNT(N,S,W,B) {W(N),S,W,B}
#define FNTD(N) {W(N),16,400,0}
#define CTYPE int
#define CBOOL CTYPE
  _CFGDEFC(0        ,OPT_CMT          ,OPF_PANE ,0,__("Looks")                                             ,__("Looks in Terminal"))
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,__("Looks")                                             ,__("Colours"))
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,3,__("Looks")                                             ,  (""))
  _CFGDEFa(colourfg ,OPT_ARR          ,OPF_H    ,0,"Colour"                   ,colour                      ,__("Colour")                   ,CLRP(0xBFBFBF,0))
  _CFGDEFb(0        ,OPT_CLR          ,OPF_CLR  ,5,"ForegroundColour"         ,colour.fg                   ,__("&Foreground...")           ,0)
  _CFGDEFb(0        ,OPT_CLR          ,OPF_CLR  ,5,"BackgroundColour"         ,colour.bg                   ,__("&Background...")           ,0)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_CLR  ,5,"CursorColour"             ,cursor_colour               ,__("CursorColour")             ,0xBFBFBF)
  _CFGDEFD(string   ,OPT_STR          ,OPF_THEME,7,"ThemeFile"                ,theme_file                  ,__("ThemeFile")                ,(""))
  _CFGDEFA(colourfg ,OPT_ARR          ,OPF_H    ,0,"ansi_colours"             ,ansi_colours[16]            ,__("ansi_colours")             ,0)
  _CFGDEFb(0        ,OPT_ARR          ,OPF_ACLR ,7,"ansi_colours"             ,ansi_colours                ,__("ansi_colours")             ,0)
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"Black"                    ,ansi_colours[BLACK_I]       ,__("Black")                    ,CLRP( RGB(  0,   0,   0), RGB(  0,   0,   0) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"Red"                      ,ansi_colours[RED_I]         ,__("Red")                      ,CLRP( RGB(212,  44,  58), RGB(162,  30,  41) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"Green"                    ,ansi_colours[GREEN_I]       ,__("Green")                    ,CLRP( RGB( 28, 168,   0), RGB( 28, 168,   0) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"Yellow"                   ,ansi_colours[YELLOW_I]      ,__("Yellow")                   ,CLRP( RGB(192, 160,   0), RGB(192, 160,   0) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"Blue"                     ,ansi_colours[BLUE_I]        ,__("Blue")                     ,CLRP( RGB(  0,  93, 255), RGB(  0,  32, 192) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"Magenta"                  ,ansi_colours[MAGENTA_I]     ,__("Magenta")                  ,CLRP( RGB(177,  72, 198), RGB(134,  54, 150) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"Cyan"                     ,ansi_colours[CYAN_I]        ,__("Cyan")                     ,CLRP( RGB(  0, 168, 154), RGB(  0, 168, 154) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"White"                    ,ansi_colours[WHITE_I]       ,__("White")                    ,CLRP( RGB(191, 191, 191), RGB(191, 191, 191) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldBlack"                ,ansi_colours[BOLD_BLACK_I]  ,__("BoldBlack")                ,CLRP( RGB( 96,  96,  96), RGB( 72,  72,  72) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldRed"                  ,ansi_colours[BOLD_RED_I]    ,__("BoldRed")                  ,CLRP( RGB(255, 118, 118), RGB(255, 118, 118) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldGreen"                ,ansi_colours[BOLD_GREEN_I]  ,__("BoldGreen")                ,CLRP( RGB(  0, 242,   0), RGB(  0, 242,   0) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldYellow"               ,ansi_colours[BOLD_YELLOW_I] ,__("BoldYellow")               ,CLRP( RGB(242, 242,   0), RGB(242, 242,   0) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldBlue"                 ,ansi_colours[BOLD_BLUE_I]   ,__("BoldBlue")                 ,CLRP( RGB(125, 151, 255), RGB(125, 151, 255) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldMagenta"              ,ansi_colours[BOLD_MAGENTA_I],__("BoldMagenta")              ,CLRP( RGB(255, 112, 255), RGB(255, 112, 255) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldCyan"                 ,ansi_colours[BOLD_CYAN_I]   ,__("BoldCyan")                 ,CLRP( RGB(  0, 240, 240), RGB(  0, 240, 240) ))
  _CFGDEFB(0        ,OPT_CLRFG|OPT_THM,OPF_H    ,0,"BoldWhite"                ,ansi_colours[BOLD_WHITE_I]  ,__("BoldWhite")                ,CLRP( RGB(255, 255, 255), RGB(255, 255, 255) ))

  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"BoldColour"               ,bold_colour                 ,__("BoldColour")               ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"BlinkColour"              ,blink_colour                ,__("BlinkColour")              ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TekForegroundColour"      ,tek_fg_colour               ,__("TekForegroundColour")      ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TekBackgroundColour"      ,tek_bg_colour               ,__("TekBackgroundColour")      ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TekCursorColour"          ,tek_cursor_colour           ,__("TekCursorColour")          ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TekWriteThruColour"       ,tek_write_thru_colour       ,__("TekWriteThruColour")       ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TekDefocusedColour"       ,tek_defocused_colour        ,__("TekDefocusedColour")       ,0xFFFFFF)
  _CFGDEFD(colour   ,OPT_INT          ,OPF_H    ,0,"TekGlow"                  ,tek_glow                    ,__("TekGlow")                  ,1)
  _CFGDEFD(colour   ,OPT_INT          ,OPF_H    ,0,"TekStrap"                 ,tek_strap                   ,__("TekStrap")                 ,0)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"UnderlineColour"          ,underl_colour               ,__("UnderlineColour")          ,0)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"HoverColour"              ,hover_colour                ,__("HoverColour")              ,0)

  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"HighlightBackgroundColour",sel_bg_colour               ,__("HighlightBackgroundColour"),0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"HighlightForegroundColour",sel_fg_colour               ,__("HighlightForegroundColour"),0xFFFFFF)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"SearchForegroundColour"   ,search_fg_colour            ,__("SearchForegroundColour")   ,0x000000)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"SearchBackgroundColour"   ,search_bg_colour            ,__("SearchBackgroundColour")   ,0x00DDDD)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"SearchCurrentColour"      ,search_current_colour       ,__("SearchCurrentColour")      ,0x0099DD)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"Background"               ,background                  ,__("Background")               ,W(""))
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"ColourScheme"             ,colour_scheme               ,__("ColourScheme")             ,"")

  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,__("Looks")                                             ,__("Transparency"))
  _CFGDEFD(CTYPE    ,OPT_TRANS        ,OPF_TRANS,7,"Transparency"             ,transparency                ,  ("")             , 0)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,__("Looks")                                             ,  (""))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"OpaqueWhenFocused"        ,opaque_when_focused         ,__("Opa&que when focused")        , 0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,3,"Blur"                     ,blurred                     ,__("Blu&r")                     , 0)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,__("Looks")                                             ,__("Cursor"))
  _CFGDEFD(CTYPE    ,OPT_CURSOR       ,OPF_LSTR ,7,"CursorType"               ,cursor_type                 ,__("CursorType")               , 0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"CursorBlinks"             ,cursor_blinks               ,__("CursorBlinks")             , 0)

  _CFGDEFC(0        ,OPT_CMT          ,OPF_H    ,0,__("Looks")                                             ,__("Disp"))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"UnderlineManual"          ,underl_manual               ,__("UnderlineManual")          , 0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"partline"                 ,partline                    ,__("partline")                 , 4)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"usepartline"              ,usepartline                 ,__("usepartline")              , 0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"Padding"                  ,padding                     ,__("Padding")                  , 1)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"DispClear"                ,disp_clear                  ,__("DispClear")                , 0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"DispTab"                  ,disp_tab                    ,__("DispTab")                  , 0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"DispSpace"                ,disp_space                  ,__("DispSpace")                , 0)

  _CFGDEFC(0        ,OPT_CMT          ,OPF_H    ,0,__("Looks")                                             ,__("Tab"))
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TabForegroundColour"      ,tab_fg_colour               ,__("TabForegroundColour")      ,0x00FF00)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TabBackgroundColour"      ,tab_bg_colour               ,__("TabBackgroundColour")      ,0x000000)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TabAttentionColour"       ,tab_attention_bg_colour     ,__("TabAttentionColour")       ,0x323232)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"TabActiveColour"          ,tab_active_bg_colour        ,__("TabActiveColour")          ,0x003200)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"tab_font_size"            ,tab_font_size               ,__("tab_font_size")            ,16)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"tab_bar_show"             ,tab_bar_show                ,__("tab_bar_show")             , 1)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_H    ,0,__("Looks")                                             ,__("indicator"))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"indicator"                ,indicator                   ,__("indicator")                , 1)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"indicatorx"               ,indicatorx                  ,__("indicatorx")               ,30)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"indicatory"               ,indicatory                  ,__("indicatory")               ,30)


  _CFGDEFC(0        ,OPT_CMT          ,OPF_H    ,0,__("Looks")                                             ,__("Dialog"))
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"gui_font_size"            ,gui_font_size               ,__("gui_font_size")            ,12)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"scale_options_width"      ,scale_options_width         ,__("scale_options_width")      ,100)

  _CFGDEFC(0        ,OPT_CMT          ,OPF_PANE ,0,__("Text")                                              ,__("Text and Font properties")    )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,__("Text")                                              ,__("Font") )
  _CFGDEFD(font_spec,OPT_FONT         ,OPF_FONT ,7,"Font"                     ,font                        ,__("Font")                     ,FNTD("Lucida Console"))
  _CFGDEFA(font_spec,OPT_ARR          ,OPF_H    ,0,""                         ,fontfams[12]                ,__("fonts")                    ,0)
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font1"                    ,fontfams[1]                 ,__("Font1")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font2"                    ,fontfams[2]                 ,__("Font2")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font3"                    ,fontfams[3]                 ,__("Font3")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font4"                    ,fontfams[4]                 ,__("Font4")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font5"                    ,fontfams[5]                 ,__("Font5")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font6"                    ,fontfams[6]                 ,__("Font6")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font7"                    ,fontfams[7]                 ,__("Font7")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font8"                    ,fontfams[8]                 ,__("Font8")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font9"                    ,fontfams[9]                 ,__("Font9")                    ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"Font10"                   ,fontfams[10]                ,__("Font10")                   ,FNTD(""))
  _CFGDEFB(0        ,OPT_FONT         ,OPF_H    ,0,"FontRTL"                  ,fontfams[11]                ,__("FontRTL")                  ,FNTD("Courier New"))

  _CFGDEFD(CTYPE    ,OPT_FONTST       ,OPF_LSTC ,7,"FontSmoothing"            ,font_smoothing              ,__("Font smoothing")           ,FS_DEFAULT)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,__("Looks")                                             ,__("Bold"))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,5,"AllowBlinking"            ,allow_blinking              ,__("AllowBlinking")            ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,5,"DimAsFont"                ,dim_as_font                 ,__("Dim as font")              ,1)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,__("Looks")                                             ,__("Bold"))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,5,"BoldAsFont"               ,bold_as_font                ,__("Bold as font")               ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,5,"BoldAsColour"             ,bold_as_colour              ,__("Bold as colour")             ,1)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,__("Text")                                              ,__("Locale") )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,__("Text")                                              ,  ("") )
  _CFGDEFD(string   ,OPT_STR          ,OPF_LCL  ,7,"Locale"                   ,locale                      ,__("Locale")                   ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_CHSET,7,"Charset"                  ,charset                     ,__("Charset")                  ,"")
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,__("Text")                                              ,__("Emojis") )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,__("Text")                                              ,  ("") )
  _CFGDEFD(CTYPE    ,OPT_EMOJIS       ,OPF_LSTC ,7,"Emojis"                   ,emojis                      ,__("Style")                   ,0)
  _CFGDEFD(CTYPE    ,OPT_EM_PLACE     ,OPF_LSTC ,7,"EmojiPlacement"           ,emoji_placement             ,__("Placement")               ,EMPL_STRETCH)

  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"FontChoice"               ,font_choice                 ,__("FontChoice")              ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"FontSample"               ,font_sample                 ,__("FontSample")              ,W(""))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ShowHiddenFonts"          ,show_hidden_fonts           ,__("ShowHiddenFonts")         ,0)
  _CFGDEFD(CTYPE    ,OPT_FONTRD       ,OPF_H    ,0,"FontRender"               ,font_render                 ,__("FontRender")              ,FR_UNISCRIBE)
  _CFGDEFD(CTYPE    ,OPT_CHARWD       ,OPF_H    ,0,"Charwidth"                ,charwidth                   ,__("Charwidth")               ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"FontMenu"                 ,fontmenu                    ,__("FontMenu")                ,-1)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"TekFont"                  ,tek_font                    ,__("TekFont")                 ,W(""))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"OldLocale"                ,old_locale                  ,__("OldLocale")               ,0)

  _CFGDEFC(0        ,OPT_CMT          ,OPF_PANE ,0,"Keys"                                                  ,__("Keyboard features")                        )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Keys"                                                  ,  ("")                                         )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,"Keys"                                                  ,  ("")                                         )
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,5,"BackspaceSendsBS"         ,backspace_sends_bs          ,__("&Backarrow sends ^H")                    ,'\b')
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,5,"DeleteSendsDEL"           ,delete_sends_del            ,__("&Delete sends DEL")                      ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"CtrlAltIsAltGr"           ,ctrl_alt_is_altgr           ,__("Ctrl+LeftAlt is Alt&Gr")                 ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"AltGrIsAlsoAlt"           ,altgr_is_alt                ,__("AltGr is also Alt")                      ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"capmapesc"                ,capmapesc                   ,__("Caplock As Escape")                      ,1) 
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"CtrlAltDelayAltGr"        ,ctrl_alt_delay_altgr        ,__("CtrlAltDelayAltGr")                      ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"KeyAlphaMode"             ,key_alpha_mode              ,__("&Esc/Enter reset IME to alphanumeric")   ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"OldAltGrDetection"        ,old_altgr_detection         ,__("OldAltGrDetection")                      ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"OldModifyKeys"            ,old_modify_keys             ,__("OldModifyKeys")                          ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"FormatOtherKeys"          ,format_other_keys           ,__("FormatOtherKeys")                        ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"AutoRepeat"               ,auto_repeat                 ,__("AutoRepeat")                             ,1)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"SupportExternalHotkeys"   ,external_hotkeys            ,__("SupportExternalHotkeys")                 ,2)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Keys"                                                  ,__("Shortcuts")                                )
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"ClipShortcuts"            ,clip_shortcuts              ,__("Cop&y and Paste (Ctrl/Shift+Ins)")       ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"WindowShortcuts"          ,window_shortcuts            ,__("&Menu and Full Screen (Alt+Space/Enter)"),1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"SwitchShortcuts"          ,switch_shortcuts            ,__("&Switch window (Ctrl+[Shift+]Tab)")      ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"ZoomShortcuts"            ,zoom_shortcuts              ,__("&Zoom (Ctrl+plus/minus/zero)")           ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"AltFnShortcuts"           ,alt_fn_shortcuts            ,__("&Alt+Fn shortcuts")                      ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"WinShortcuts"             ,win_shortcuts               ,__("&Win+x shortcuts")                       ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"CtrlShiftShortcuts"       ,ctrl_shift_shortcuts        ,__("&Ctrl+Shift+letter shortcuts")           ,0)
  _CFGDEFD(CTYPE    ,OPT_COMPKEY      ,OPF_LSTC ,7,"ComposeKey"               ,compose_key                 ,__("Compose key")                            ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ZoomFontWithWindow"       ,zoom_font_with_window       ,__("ZoomFontWithWindow")                     ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"hkwinkeyall"              ,hkwinkeyall                 ,__("hkwinkeyall")                            ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"hook_keyboard"            ,hook_keyboard               ,__("hook_keyboard")                          ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"CtrlExchangeShift"        ,ctrl_exchange_shift         ,__("CtrlExchangeShift")                      ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"CtrlControls"             ,ctrl_controls               ,__("CtrlControls")                           ,0)
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"Key_PrintScreen"          ,key_prtscreen               ,__("Key_PrintScreen")                        ,"")    // VK_SNAPSHOT
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"Key_Pause"                ,key_pause                   ,__("Key_Pause")                              ,"")  // VK_PAUSE
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"Key_Break"                ,key_break                   ,__("Key_Break")                              ,"")  // VK_CANCEL
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"Key_Menu"                 ,key_menu                    ,__("Key_Menu")                               ,"")    // VK_APPS
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"Key_ScrollLock"           ,key_scrlock                 ,__("Key_ScrollLock")                         ,"")    // VK_SCROLL
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"KeyFunctions"             ,key_commands                ,__("KeyFunctions")                           ,W(""))
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"ManageLEDs"               ,manage_leds                 ,__("ManageLEDs")                             ,7)
//_CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ShootFoot"                ,enable_remap_ctrls          ,__("ShootFoot")                              ,0)
//_CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"OldKeyFunctionsKeypad"    ,old_keyfuncs_keypad         ,__("OldKeyFunctionsKeypad")                  ,0)

  _CFGDEFC(0        ,OPT_CMT          ,OPF_PANE ,0,"Mouse"                                                 ,__("Mouse functions")            )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Mouse"                                                 ,  ("")                           )
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,0,"ClicksPlaceCursor"        ,clicks_place_cursor         ,__("Clic&ks place command line cursor")  ,0)
  _CFGDEFD(string   ,OPT_STR          ,OPF_STR  ,7,"WordCharsExcl"            ,word_chars_excl             ,__("Delimiters:")                        ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_STR  ,7,"WordChars"                ,word_chars                  ,__("Word Characters:")                   ,"")
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Mouse"                                                 ,__("Click actions")                         )
  _CFGDEFD(CTYPE    ,OPT_RTCLICK      ,OPF_LSTR ,7,"RightClickAction"         ,right_click_action          ,__("Right mouse button")                 ,RC_MENU)
  _CFGDEFD(CTYPE    ,OPT_MDCLICK      ,OPF_LSTR ,7,"MiddleClickAction"        ,middle_click_action         ,__("Middle mouse button")                ,MC_PASTE)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"ClicksTargetApp"          ,clicks_target_app           ,__("Clicks Send to App")                 ,1)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,9,"Mouse"                                                 ,__("Modifier for overriding default")    )
  _CFGDEFD(CTYPE    ,OPT_MOD          ,OPF_LSTR ,9,"ClickTargetMod"           ,click_target_mod            ,  ("")    ,MDK_SHIFT)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"OpeningClicks"            ,opening_clicks              ,__("OpeningClicks")                      ,1)
  _CFGDEFD(CTYPE    ,OPT_MOD          ,OPF_H    ,0,"OpeningMod"               ,opening_mod                 ,__("OpeningMod")                         ,MDK_CTRL)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ZoomMouse"                ,zoom_mouse                  ,__("ZoomMouse")                          ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"HideMouse"                ,hide_mouse                  ,__("HideMouse")                          ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ElasticMouse"             ,elastic_mouse               ,__("ElasticMouse")                       ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"LinesPerMouseWheelNotch"  ,lines_per_notch             ,__("LinesPerMouseWheelNotch")            ,0)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"MousePointer"             ,mouse_pointer               ,__("MousePointer")                       ,W("ibeam"))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"AppMousePointer"          ,appmouse_pointer            ,__("AppMousePointer")                    ,W("arrow"))

  _CFGDEFC(0        ,OPT_CMT          ,OPF_PANE ,0,"Selection"                                             ,__("Selection and clipboard")              ) 
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Selection"                                             ,  ("")                                     )
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"ClearSelectionOnInput"    ,input_clears_selection      ,__("Clear selection on input")           ,1)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,7,"Selection"                                             ,__("Clipboard")                            )
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"CopyOnSelect"             ,copy_on_select              ,__("Cop&y on select")                    ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"CopyTab"                  ,copy_tabs                   ,__("Copy with TABs")                     ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"CopyAsRTF"                ,copy_as_rtf                 ,__("Copy as &rich text")                 ,1)
  _CFGDEFD(CTYPE    ,OPT_CPYHTML      ,OPF_LSTR ,7,"CopyAsHTML"               ,copy_as_html                ,__("CopyAsHTML")                         ,0)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"CopyAsRTFFont"            ,copy_as_rtf_font            ,__("CopyAsRTFFont")                      ,W(""))
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"CopyAsRTFFontHeight"      ,copy_as_rtf_font_size       ,__("CopyAsRTFFontHeight")                ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,0,"TrimSelection"            ,trim_selection              ,__("Trim space from selection")          ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,0,"AllowSetSelection"        ,allow_set_selection         ,__("Allow setting selection")            ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"AllowPasteSelection"      ,allow_paste_selection       ,__("allow_paste_selection")              ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_INT  ,2,"SelectionShowSize"        ,selection_show_size         ,__("Show size while selecting (0..12)")  ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_INT  ,2,"SuspendWhileSelecting"    ,suspbuf_max                 ,__("Suspend output while selecting")     ,8080)

  _CFGDEFC(0        ,OPT_CMT          ,OPF_PANE ,0,"Window"                                                ,__("Window Options")                     )  
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Window"                                                ,__("Default size")                            )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,"Window"                                                ,  ("")                            )
  _CFGDEFB(int      ,OPT_INT          ,OPF_INT  ,5,"Columns"                  ,winsize.x                   ,__("Colu&mns")                           ,80)
  _CFGDEFB(int      ,OPT_INT          ,OPF_INT  ,5,"Rows"                     ,winsize.y                   ,__("Ro&ws")                              ,24)
  _CFGDEFA(intpair  ,OPT_INTP         ,OPF_WSIZE,5,"winsize"                  ,winsize                     ,__("C&urrent size")                      ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,0,"RewrapOnResize"           ,rewrap_on_resize            ,__("Re&wrap on resize")                  ,0)
  _CFGDEFD(CTYPE    ,OPT_SCRLBAR      ,OPF_LSTR ,7,"Scrollbar"                ,scrollbar                   ,__("Scrollbar")                          ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_INT  ,5,"ScrollbackLines"          ,scrollback_lines            ,__("Scroll&back lines")                  ,50000)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"MaxScrollbackLines"       ,max_scrollback_lines        ,__("MaxScrollbackLines")                 ,250000)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,9,"Window"                                                ,__("Modifier for scrolling")             )
  _CFGDEFD(CTYPE    ,OPT_MOD          ,OPF_LSTR ,9,"ScrollMod"                ,scroll_mod                  ,  ("")             ,MDK_SHIFT)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"PgUpDnScroll"             ,pgupdn_scroll               ,__("&PgUp and PgDn scroll without modifier")       ,0)
  _CFGDEFD(CTYPE    ,OPT_BORDER       ,OPF_LSTR ,7,"BorderStyle"              ,border_style                ,__("BorderStyle")                                  ,BORDER_NORMAL)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,0,"allocconsole"             ,allocconsole                ,__("&AllocConsole ,Some console programs need it."),0)
//_CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Window"                                                ,__("UI language")                            )
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"Language"                 ,lang                        ,__("Language")                 ,(""))

//_CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Window"                                                ,__("Search Bar")               )
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"SearchBar"                ,search_bar                  ,__("Search Bar")               ,W(""))
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"SearchContext"            ,search_context              ,__("SearchContext")            ,0)

  _CFGDEFC(0        ,OPT_CMT          ,OPF_PANE ,0,"Terminal"                                              ,__("Terminal features")         )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Terminal"                                              ,  ("")                          )
  _CFGDEFC(0        ,OPT_CMT          ,OPF_COL  ,2,"Terminal"                                              ,  ("")                          )
  _CFGDEFD(string   ,OPT_STR          ,OPF_TERM ,6,"Term"                     ,Term                        ,__("Term")                     ,"xterm")
  _CFGDEFD(string   ,OPT_STR          ,OPF_STR  ,8,"Answerback"               ,answerback                  ,__("&Answerback")              ,"")
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"WrapTab"                  ,wrap_tab                    ,__("WrapTab")                  ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"OldWrapModes"             ,old_wrapmodes               ,__("OldWrapModes")             ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"Enable132ColumnSwitching" ,enable_deccolm_init         ,__("Enable132ColumnSwitching") ,0)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,0,"Terminal"                                              ,__("Bell")                          )
  _CFGDEFD(int      ,OPT_INT          ,OPF_BELL ,7,"BellType"                 ,bell_type                   ,__("BellType")                 ,1)
  _CFGDEFA(string   ,OPT_ARR          ,OPF_H    ,0,""                         ,bell_file[7]                ,__("BellFiles")                ,0)
  _CFGDEFB(string   ,OPT_STR          ,OPF_BELLF,7,"BellFile"                 ,bell_file[6]                ,__("BellFile")                 ,"")
  _CFGDEFB(string   ,OPT_STR          ,OPF_H    ,0,"BellFile2"                ,bell_file[0]                ,__("BellFile2")                ,"")
  _CFGDEFB(string   ,OPT_STR          ,OPF_H    ,0,"BellFile3"                ,bell_file[1]                ,__("BellFile3")                ,"")
  _CFGDEFB(string   ,OPT_STR          ,OPF_H    ,0,"BellFile4"                ,bell_file[2]                ,__("BellFile4")                ,"")
  _CFGDEFB(string   ,OPT_STR          ,OPF_H    ,0,"BellFile5"                ,bell_file[3]                ,__("BellFile5")                ,"")
  _CFGDEFB(string   ,OPT_STR          ,OPF_H    ,0,"BellFile6"                ,bell_file[4]                ,__("BellFile6")                ,"")
  _CFGDEFB(string   ,OPT_STR          ,OPF_H    ,0,"BellFile7"                ,bell_file[5]                ,__("BellFile7")                ,"")
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"BellFreq"                 ,bell_freq                   ,__("BellFreq")                 ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"BellLen"                  ,bell_len                    ,__("BellLen")                  ,400)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"BellFlash"                ,bell_flash                  ,__("&Flash")               ,0)// xterm: visualBell
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"BellFlashStyle"           ,bell_flash_style            ,__("BellFlashStyle")           ,FLASH_FULL)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"BellTaskbar"              ,bell_taskbar                ,__("&Highlight in taskbar")    ,1)// xterm: bellIsUrgent
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"BellPopup"                ,bell_popup                  ,__("&Popup")               ,0)// xterm: popOnBell
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"BellInterval"             ,bell_interval               ,__("BellInterval")             ,100)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"PlayTone"                 ,play_tone                   ,__("PlayTone")                 ,2)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_PRINT,7,"Printer"                  ,printer                     ,__("Printer")                  ,W(""))
  _CFGDEFC(0        ,OPT_CMT          ,OPF_GRP  ,7,"Terminal"                                              ,  ("")                        )
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"ConfirmExit"              ,confirm_exit                ,__("Prompt about running processes on &close"),1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_CHK  ,7,"StatusLine"               ,status_line                 ,__("Status Line")               ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ConfirmReset"             ,confirm_reset               ,__("ConfirmReset")             ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ConfirmMultiLinePasting"  ,confirm_multi_line_pasting  ,__("ConfirmMultiLinePasting")  ,0)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_H    ,0,"Command line"                                          ,__("Command line Options"))  // 
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"Class"                    ,class                       ,__("Class")                    ,W(""))
  _CFGDEFD(CTYPE    ,OPT_HOLD         ,OPF_H    ,0,"Hold"                     ,hold                        ,__("Hold")                     ,HOLD_START)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ExitWrite"                ,exit_write                  ,__("ExitWrite")                ,0)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"ExitTitle"                ,exit_title                  ,__("ExitTitle")                ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"Icon"                     ,icon                        ,__("Icon")                     ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"Log"                      ,log                         ,__("Log")                      ,W(""))
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"Logging"                  ,logging                     ,__("Logging")                  ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"Utmp"                     ,create_utmp                 ,__("Utmp")                     ,0)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"Title"                    ,title                       ,__("Title")                    ,W(""))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"title_settable"           ,title_settable              ,__("title_settable")           ,1)
  _CFGDEFD(CTYPE    ,OPT_WINDOW       ,OPF_H    ,0,"Window"                   ,window                      ,__("Window")                   ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"X"                        ,x                           ,__("X")                        ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"Y"                        ,y                           ,__("Y")                        ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"Daemonize"                ,daemonize                   ,__("Daemonize")                ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"DaemonizeAlways"          ,daemonize_always            ,__("DaemonizeAlways")          ,0)
  _CFGDEFC(0        ,OPT_CMT          ,OPF_H    ,0,"Hidden"                                                ,__("Hidden Options"))  
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"Bidi"                     ,bidi                        ,__("Bidi")                     ,2)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"NoAltScreen"              ,disable_alternate_screen    ,__("NoAltScreen")              ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"EraseToScrollback"        ,erase_to_scrollback         ,__("EraseToScrollback")        ,1)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"DisplaySpeedup"           ,display_speedup             ,__("DisplaySpeedup")           ,6)
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"SuppressSGR"              ,suppress_sgr                ,__("SuppressSGR")              ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"SuppressDEC"              ,suppress_dec                ,__("SuppressDEC")              ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"SuppressWIN"              ,suppress_win                ,__("SuppressWIN")              ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"SuppressOSC"              ,suppress_osc                ,__("SuppressOSC")              ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"SuppressNRC"              ,suppress_nrc                ,__("SuppressNRC")              ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"SuppressMouseWheel"       ,suppress_wheel              ,__("SuppressMouseWheel")       ,"")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"FilterPasteControls"      ,filter_paste                ,__("FilterPasteControls")      ,"STTY")
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"GuardNetworkPaths"        ,guard_path                  ,__("GuardNetworkPaths")               ,7)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"BracketedPasteByLine"     ,bracketed_paste_split       ,__("BracketedPasteByLine")     ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"PrintableControls"        ,printable_controls          ,__("PrintableControls")        ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"CharNarrowing"            ,char_narrowing              ,__("CharNarrowing")            ,75)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"SaveFilename"             ,save_filename               ,__("SaveFilename")             ,W("mintty.%Y-%m-%d_%H-%M-%S"))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"AppID"                    ,app_id                      ,__("AppID")                    ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"AppName"                  ,app_name                    ,__("AppName")                  ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"AppLaunchCmd"             ,app_launch_cmd              ,__("AppLaunchCmd")             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"DropCommands"             ,drop_commands               ,__("DropCommands")             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"ExitCommands"             ,exit_commands               ,__("ExitCommands")             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"UserCommands"             ,user_commands               ,__("UserCommands")             ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"CtxMenuFunctions"         ,ctx_user_commands           ,__("CtxMenuFunctions")         ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"SysMenuFunctions"         ,sys_user_commands           ,__("SysMenuFunctions")         ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"UserCommandsPath"         ,user_commands_path          ,__("UserCommandsPath")         ,W("/bin:%s"))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"SessionCommands"          ,session_commands            ,__("SessionCommands")          ,W(""))
  _CFGDEFD(wstring  ,OPT_WSTR|OPT_KCR ,OPF_H    ,0,"TaskCommands"             ,task_commands               ,__("TaskCommands")             ,W(""))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ConPTY"                   ,conpty_support              ,__("ConPTY")                   ,-1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"LoginFromShortcut"        ,login_from_shortcut         ,__("LoginFromShortcut")        ,1)
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"MenuMouse"                ,menu_mouse                  ,__("MenuMouse")                ,"b")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"MenuCtrlMouse"            ,menu_ctrlmouse              ,__("MenuCtrlMouse")            ,"e|ls")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"MenuMouse5"               ,menu_altmouse               ,__("MenuMouse5")               ,"ls"  )
//_CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"MenuMenu"                 ,menu_menu                   ,__("MenuMenu")                 ,"bs"  )
//_CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"MenuCtrlMenu"             ,menu_ctrlmenu               ,__("MenuCtrlMenu")             ,"e|ls")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"MenuTitleCtrlLeft"        ,menu_title_ctrl_l           ,__("MenuTitleCtrlLeft")        ,"Ws")
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"MenuTitleCtrlRight"       ,menu_title_ctrl_r           ,__("MenuTitleCtrlRight")       ,"Ws")
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"SessionGeomSync"          ,geom_sync                   ,__("SessionGeomSync")          ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"ColSpacing"               ,col_spacing                 ,__("ColSpacing")               ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"RowSpacing"               ,row_spacing                 ,__("RowSpacing")               ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"AutoLeading"              ,auto_leading                ,__("AutoLeading")              ,2)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"Ligatures"                ,ligatures                   ,__("Ligatures")                ,1)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"LigaturesSupport"         ,ligatures_support           ,__("LigaturesSupport")         ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"BoxDrawing"               ,box_drawing                 ,__("BoxDrawing")               ,1)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"HandleDPI"                ,handle_dpichanged           ,__("HandleDPI")                ,2)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"CheckVersionUpdate"       ,check_version_update        ,__("CheckVersionUpdate")       ,0)
  _CFGDEFD(colour   ,OPT_CLR          ,OPF_H    ,0,"IMECursorColour"          ,ime_cursor_colour           ,__("IMECursorColour")          ,DEFAULT_COLOUR)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"SixelClipChars"           ,sixel_clip_char             ,__("SixelClipChars")           ,W(""))
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"OldBold"                  ,old_bold                    ,__("OldBold")                  ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ShortLongOpts"            ,short_long_opts             ,__("ShortLongOpts")            ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"BoldAsRainbowSparkles"    ,bold_as_special             ,__("BoldAsRainbowSparkles")    ,0)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"HoverTitle"               ,hover_title                 ,__("HoverTitle")               ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"ProgressBar"              ,progress_bar                ,__("ProgressBar")              ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"ProgressScan"             ,progress_scan               ,__("ProgressScan")             ,1)
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"DimMargins"               ,dim_margins                 ,__("DimMargins")               ,0)
//_CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"StatusDebug"              ,status_debug                ,__("status_debug")             ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"Baud"                     ,baud                        ,__("Baud")                     ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"Bloom"                    ,bloom                       ,__("Bloom")                    ,0)
  _CFGDEFD(wstring  ,OPT_WSTR         ,OPF_H    ,0,"OptionsFont"              ,options_font                ,__("OptionsFont")              ,W(""))
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"OptionsFontHeight"        ,options_fontsize            ,__("OptionsFontHeight")        ,0)
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"OldOptions"               ,old_options                 ,__("OldOptions")               ,"")
  _CFGDEFD(CBOOL    ,OPT_BOOL         ,OPF_H    ,0,"OldXButtons"              ,old_xbuttons                ,__("OldXButtons")              ,0)
  _CFGDEFD(int      ,OPT_INT          ,OPF_H    ,0,"WSLBridge"                ,wslbridge                   ,__("wslbridge version,0:nobridge,1:wslbridge,2:wslbreadge2") ,0)
  _CFGDEFD(string   ,OPT_STR          ,OPF_H    ,0,"WSLName"                  ,wslname                     ,__("wslDistribution,null is default") ,"")
  // Legacy                                      0,
  _CFGDEFE(int      ,OPT_INT|OPT_LG   ,OPF_H    ,0,"FontSize"                 ,font.size                   ,__("FontSize")                 )
  _CFGDEFE(string   ,OPT_STR|OPT_LG   ,OPF_H    ,0,"Break"                    ,key_break                   ,__("Break")                    )
  _CFGDEFE(string   ,OPT_STR|OPT_LG   ,OPF_H    ,0,"Pause"                    ,key_pause                   ,__("Pause")                    )
  _CFGDEFE(int      ,OPT_INT|OPT_LG   ,OPF_H    ,0,"CopyAsRTFFontSize"        ,copy_as_rtf_font_size       ,__("CopyAsRTFFontSize")        )
  _CFGDEFE(int      ,OPT_INT|OPT_LG   ,OPF_H    ,0,"OldFontMenu"              ,fontmenu                    ,__("OldFontMenu")              )
  _CFGDEFE(int      ,OPT_INT|OPT_LG   ,OPF_H    ,0,"OptionsFontSize"          ,options_fontsize            ,__("OptionsFontSize")          )
  _CFGDEFE(CBOOL    ,OPT_BOOL|OPT_LG  ,OPF_H    ,0,"BoldAsBright"             ,bold_as_colour              ,__("BoldAsBright")             )
  _CFGDEFE(CTYPE    ,OPT_FONTST|OPT_LG,OPF_H    ,0,"FontQuality"              ,font_smoothing              ,__("FontQuality")              )
  _CFGDEFD(colour   ,OPT_BOOL|OPT_LG  ,OPF_H    ,0,"UseSystemColours"         ,use_system_colours          ,__("UseSystemColours")         ,0)
#undef CFGDEFT  
#undef _CFGDEFA
#undef _CFGDEFB
#undef _CFGDEFa
#undef _CFGDEFb
#undef _CFGDEFC
#undef _CFGDEFD
#undef _CFGDEFE
#undef DEFVAR 
#undef DEFVAL 
#undef DEFCFG 
#endif
